export AWS_REGION="your-aws-region"
export OPENSEARCH_SECRET="your-opensearch-secret"
export OPENSEARCH_DOMAIN_ENDPOINT="your-opensearch-url"
export OPENSEARCH_INDEX="llm_rag_embeddings"
export EMBEDDING_ENDPOINT_NAME="your-sagemaker-endpoint-for-embedding-model"
export TEXT2TEXT_ENDPOINT_NAME="your-sagemaker-endpoint-for-text-generation-model"