name: streamlit-env
channels:
  - conda-forge
dependencies:
  - python=3.12
  - pip
  - mamba
  - pip:
      - boto3>=1.26.159
      - langchain==0.1.11
      - langchain-community==0.0.29
      - sqlalchemy==2.0.2
      - opensearch-py==2.2.0
      - streamlit==1.32.2
